# Header

menu:
  主页: https://plusplus7.com
  杂物间: https://plusplus7.com/storage

# SubNav
subnav:
  github: "https://github.com/plusplus7"
  weibo: "https://weibo.com/plusplus7"
  rss: "/atom.xml"
  zhihu: "https://www.zhihu.com/people/plusplus7"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: "https://space.bilibili.com/1438242"
  #acfun: "#"
  mail: "mailto:jackiedeng.cn@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  linkedin: "https://www.linkedin.com/in/jackiedeng"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我喝咖啡'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay-donate.png
# 微信二维码图片地址
weixin: /img/weixin-donate.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/avatar.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: true

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '文章列表'
  friends: '友情链接'
  aboutme: '关于我'

friends:
  ACM/ICPC解题报告: http://blog.csdn.net/sssogs/
  Prince Laharl: http://prince-laharl.github.io/
  Fluyy: http://fluyy.net/
  豆腐: http://uazw.github.io/
  CUIT ACM校队: http://acm.cuit.edu.cn/
  JoyChou: https://joychou.org/

aboutme: 网络ID是plusplus7, 简称+7<br>本职是后台开发工程师, 业余游戏解说, 游戏主播<br>喜欢玩电子游戏，喜欢算法和数学<br>喜欢用轻松的文字来记录学习工作生活中的点点滴滴<br>我是+7，我热爱生活，我对我的人生负责
